/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System.Collections.Generic;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;

namespace SimpleKitingN
{
    public class BotEntryPoint : RGBehaviorTreeBot
    {
        protected override bool GetIsSpawnable() => true;
        protected override RGBotLifecycle GetBotLifecycle() => RGBotLifecycle.MANAGED;

        private const string CharacterConfig = @"{}";

        public override void ConfigureBot(RG rgObject)
        {
            rgObject.SetCharacterConfigFromJson(CharacterConfig);
        }

        protected override RootNode BuildBehaviorTree()
        {
            var moveLogic = new SequenceNode("Move logic");
            moveLogic.AddChild(new IfNotNearTargetLocation());
            moveLogic.AddChild(new MoveToTarget());
            var attackOrMove = new SelectorNode("Attack OR Move");
            attackOrMove.AddChild(moveLogic);
            attackOrMove.AddChild(new AttackTheEnemy());
            var topLevelSequenceNode = new SequenceNode("Top Level Sequence Node");
            topLevelSequenceNode.AddChild(new IfTheBotIsActive());
            topLevelSequenceNode.AddChild(new IfTheBotIsNotAttacking());
            topLevelSequenceNode.AddChild(attackOrMove);
            var rootNode = new RootNode();
            rootNode.AddChild(topLevelSequenceNode);

            return rootNode;
        }
    }
}