/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace SimpleKitingN
{
    public class AttackTheEnemy : ActionNode
    {
        public AttackTheEnemy() : base("Attack the enemy")
        {
        }

        /**
         * Generated from prompt:
         * Attack the closest enemy.
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var myPlayer = rgObject.GetMyPlayer();
        	var nearestEnemy = rgObject.FindNearestEntityByName("Enemy", position: myPlayer.position);
        	if (nearestEnemy == null)
        		return NodeStatus.Failure;
        	var actionParams = new Dictionary<string, object> { { "enemyId", nearestEnemy.id }, { "ability", 0 } };
        	rgObject.PerformAction(new RGActionRequest("SelectAndAttackEnemy", actionParams));
        	return NodeStatus.Success;
        }
    }
}