/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace SampleBot_160
{
    public class IfTheBotIsNotAttacking : ConditionNode
    {
        public IfTheBotIsNotAttacking() : base("If the bot is not attacking")
        {
        }

        /**
         * Generated from prompt:
         * Return failure if the bot is currently attacking.
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var player = rgObject.GetMyPlayer();
        	var isAttacking = player.GetField<bool>("IsAttacking");
        	if (isAttacking)
        	{
        		return NodeStatus.Failure;
        	}
        	else
        	{
        		return NodeStatus.Success;
        	}
        }
    }
}