/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;
using FirstBotDemo;
using RegressionGames;

namespace SimpleKitingN
{
    public class IfTheBotIsNotAttacking : ConditionNode
    {
        public IfTheBotIsNotAttacking() : base("If the bot is not attacking")
        {
        }

        /**
         * Generated from prompt:
         * Return failure if the bot is currently attacking.
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var playerAttack = rgObject.GetMyPlayer().GetFields<RGStateEntity_PlayerAttack>().FirstOrDefault();
        	if(playerAttack.IsAttacking) return NodeStatus.Failure;
        	return NodeStatus.Success;
        }
    }
}