/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace SimpleKitingN
{
    public class IfTheBotIsActive : ConditionNode
    {
        public IfTheBotIsActive() : base("If the bot is active")
        {
        }

        /**
         * Generated from prompt:
         * Return success if the bot exists - otherwise, return null.
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var bot = rgObject.GetMyPlayer();
        	return bot != null ? NodeStatus.Success : NodeStatus.Failure;
        }
    }
}